<?php
/**
 * @package WordPress
 * @subpackage Constructor
 * @link http://www.google.com/webfonts
 * @update 2011.03.30
 * @todo More flexible
 */
return array(
    'Aclonica',
    //'Allan',// 700 weight
    'Allerta',
    '"Allerta Stencil"',
    'Amaranth',
    '"Annie Use Your Telescope"',
    '"Anonymous Pro"',
    'Anton',
    '"Architects Daughter"',
    'Arimo', // Regular / Italic / Bold / Bold Italic
    'Arvo', // Regular / Italic / Bold / Bold Italic
    'Artifika',
    'Asset',
    'Astloch',
    'Bentham',
    'Bevan',
    '"Bigshot One"',
    'Brawler',
    //'Buda', // 300 weight
    'Cabin',
    //'"Cabin Sketch"',// 700 weight
    'Calligraffitti',
    'Candal',
    'Cantarell', // Regular / Italic / Bold / Bold Italic
    'Cardo',
    '"Carter One"',
    'Caudex',
    '"Cedarville Cursive"',
    '"Cherry Cream Soda"',
    'Chewy',
    //'Coda',// 800 weight
    '"Coming Soon"',
    'Copse',
    'Cousine', // Regular / Italic / Bold / Bold Italic
    '"Covered By Your Grace"',
    '"Crafty Girls"',
    '"Crimson Text"',
    'Crushed',
    'Cuprum',
    'Damion',
    '"Dancing Script"',
    '"Dawning of a New Day"',
    '"Didact Gothic"',
    '"Droid Sans"',      // Regular / Bold
    '"Droid Sans Mono"',
    '"Droid Serif"',
    '"EB Garamond"',
    '"Expletus Sans"',
    '"Fontdiner Swanky"',
    '"Francois One"',
    'Geo',
    '"Goblin One"',
    '"Goudy Bookletter 1911"',
    '"Gravitas One"',
    'Gruppo',
    '"Hammersmith One"',
    '"Holtwood One SC"',
    '"Homemade Apple"',
    // "IM Fell" family
    '"IM Fell English"',
    '"IM Fell Double Pica"',
    'Inconsolata',
    '"Indie Flower"',
    '"Irish Grover"',
    '"Josefin Sans"',
    '"Josefin Slab"',
    'Judson',
    'Jura',
    '"Just Another Hand"',
    '"Just Me Again Down Here"',
    'Kameron',
    'Kenia',
    'Kranky',
    'Kreon',
    'Kristi',
    '"La Belle Aurore"',
    'Lato',
    '"League Script"',
    'Lekton',
    'Limelight',
    'Lobster',
    '"Lobster Two"',
    'Lora',
    '"Luckiest Guy"',
    'Mako',
    '"Maven Pro"',
    'Meddon',
    'MedievalSharp',
    'Megrim',
    'Merriweather',
    'Metrophobic',
    'Michroma',
    'Miltonian',
    '"Miltonian Tattoo"',
    'Molengo',
    'Monofett',
    '"Mountains of Christmas"',
    'Muli',
    'Neucha',
    'Neuton',
    '"News Cycle"',
    'Nobile',
    //'Nova', // 100 weight
    '"Nova Square"',
    '"Nova Oval"',
    '"Nova Cut"',
    '"Nova Round"',
    '"Nova Script"',
    '"Nova Mono"',
    'Nunito',
    '"OFL Sorts Mill Goudy TT"',
    '"Old Standard TT"',
    'Orbitron',
    'Oswald',
    '"Over the Rainbow"',
    'Pacifico',
    '"Paytone One"',
    '"Permanent Marker"',
    'Philosopher',
    'Play',
    '"Playfair Display"',
    'Podkova',
    '"PT Sans"',
    '"PT Serif"',
    'Puritan',
    'Quattrocento',
    '"Quattrocento Sans"',
    'Radley',
    //'Raleway', // 100 weight
    'Redressed',
    '"Reenie Beanie"',
    '"Rock Salt"',
    'Rokkitt',
    '"Ruslan Display"',
    'Schoolbell',
    '"Shadows Into Light"',
    'Shanti',
    '"Sigmar One"',
    '"Six Caps"',
    'Slackey',
    'Smythe',
    //'Sniglet', // 800 weight
    '"Special Elite"',
    '"Sue Ellen Francisco"',
    'Sunshiney',
    'Syncopate',
    '"Swanky and Moo Moo"',
    'Tangerine',
    '"Tenor Sans"',
    '"Terminal Dosis Light"',
    '"The Girl Next Door"',
    'Tinos',
    'Ubuntu',
    'Ultra',
    //'UnifrakturCook', // 700 weight
    'UnifrakturMaguntia',
    'Unkempt',
    'Varela',
    'Vibur',
    'Vollkorn',
    'VT323',
    '"Waiting for the Sunrise"',
    '"Walter Turncoat"',
    'Wallpoet',
    '"Wire One"',
    '"Yanone Kaffeesatz"',
    'Zeyada'
);
?>